### ISSUE TITLE
More event.preventDefault() on right click

### ISSUE THREAD

**Issue by erikquinn** [CaptainTux/VATSIM_EDST_frontend#12]
There are many elements you are able to right-click where you get the native right-click menu. Given the frequency of right-click actions throughout the app, the right-click default behavior should be disabled globally. I can't remember for sure, but I think you might be able to just put an e.preventDefault() on the window, ie:

`window.addEventListener("contextmenu", e => e.preventDefault());`

It may be more complex than that, but I think you can just do that! 🤞

**Comment by CaptainTux** [comment]
fixed in commit `5ad71b26ccc630fef344333764b0125c01dc64dc` on `dev.ts` branch, closing
