### ISSUE TITLE
[ToolTips] Plan Options not pointed at right buttons

### ISSUE THREAD

**Issue by KSanders7070** [CaptainTux/VATSIM_EDST_frontend#18]
The following buttons, if assigned, are assigned to the regular ACL/DCL but should be assigned to the Plan Options Menu:

plan_options_alt
plan_options_speed
plan_options_route
plan_options_prev_route
plan_options_stop_probe
plan_options_trial_restr
plan_options_plans
plan_options_keep
plan_options_delete

**Comment by KSanders7070** [comment]
you can keep these descriptions in the main ACL/DCL list too, but they need to be also in the plan options menus

**Comment by CaptainTux** [comment]
closed in [commit](https://github.com/CaptainTux/VATSIM_EDST_frontend/commit/7efa45a38eae3c47b614305368f2076039b79408)
