### ISSUE TITLE
[SV & FA Icons] Updated

### ISSUE THREAD

**Issue by KSanders7070** [CaptainTux/VATSIM_EDST_frontend#23]
attached
![SV2](https://user-images.githubusercontent.com/63331106/152997874-3d50d5c2-4222-4600-8425-8e084adffb2e.png)
![SV1](https://user-images.githubusercontent.com/63331106/152997877-e7865d23-49b5-405f-ba7c-296fed2dec97.png)
![FA](https://user-images.githubusercontent.com/63331106/152997879-940558cb-c510-4141-bb56-d07f8b248f58.png)

**Comment by CaptainTux** [comment]
updated in commit `8426f4af9b43d7c2a2f0fc627d38acf5f0f8b62d`
